Repository cdklabs/github-merit-badger, pull requests merged in 2024-04, with the labels that each got.

#3 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  package.json
  yarn.lock
Labels: auto-approve, first

#7 chore(deps): upgrade dependencies
  dist/index.js
  dist/index.js.map
  yarn.lock
Labels: auto-approve, second

#8 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#9 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#10 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#12 chore: allow bot to auto-approve upgrades
  .github/workflows/auto-approve.yml
  .projenrc.ts
Labels: first

#13 fix: incorrect token in auto-approve settings
  .github/workflows/auto-approve.yml
  .projenrc.ts
Labels: second

#11 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#14 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#15 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#16 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#17 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#18 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#19 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#20 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#21 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#22 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third

#23 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, third
